<a href="https://colab.research.google.com/github/ass007-mouele/python/blob/master/Ass_Linear_regression_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Execute the code below

In [221]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/weather2019.csv"
df_weather = pd.read_csv(link)
df_weather['couleur']=pd.DataFrame({'couleur':['r','b','y']})
df_weather['couleur'].fillna(0,inplace=True)
df_weather

           DATE  MAX_TEMPERATURE_C  MIN_TEMPERATURE_C  ...  MONTH  DAY  couleur
0    2019-01-01                  9                  4  ...      1    1        r
1    2019-01-02                  8                  5  ...      1    2        b
2    2019-01-03                  6                  0  ...      1    3        y
3    2019-01-04                  5                 -1  ...      1    4        0
4    2019-01-05                  6                 -1  ...      1    5        0
..          ...                ...                ...  ...    ...  ...      ...
360  2019-12-27                 13                 10  ...     12   27        0
361  2019-12-28                 11                  5  ...     12   28        0
362  2019-12-29                  9                  2  ...     12   29        0
363  2019-12-30                 12                  4  ...     12   30        0
364  2019-12-31                 10                  4  ...     12   31        0

[365 rows x 25 columns]

In [0]:
# Your code here :
#from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split

X = df_weather[['MAX_TEMPERATURE_C','MIN_TEMPERATURE_C']]
y = df_weather['SUNHOUR']

X_train,X_test,y_train,y_test=train_test_split(X, y,random_state=1, train_size=0.80)

modelLRKNN = KNeighborsRegressor(n_neighbors=13).fit(X_train ,y_train)

In [0]:
from sklearn.linear_model import LinearRegression

modelLR = LinearRegression().fit(X_train ,y_train)

In [224]:
from sklearn.metrics import r2_score

print("Comparaison : \n")

print("Linear regression score with KNN : " ,modelLRKNN.score(X_test, y_test))
print("Linear regression score without KNN : ",modelLR.score(X_test, y_test))

Comparaison :

Linear regression score with KNN :  0.6106100759852853
Linear regression score without KNN :  0.5723688087207219

In [225]:
y_pred=modelLRKNN.predict(X_test)
y_pred1=modelLR.predict(X_test)
print("Linear regression score with KNN : ", r2_score(y_test, y_pred))
print("Linear regression score without KNN : ",r2_score(y_test, y_pred1))

Linear regression score with KNN :  0.6106100759852853
Linear regression score without KNN :  0.5723688087207219